class Table {
  deck : number[]
  turnHolder : number
  activePlayers : Player[]
  dealerHand : number[]
  dealerScore : number
  state : string
  resetTable()
}

class Player {
  id : string
  hand : number[]
  score : number
  bet : number
  balance : number
  nickname : string
  resetHand()
}

Table o- Player
